/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-15 04:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.vo.MemberVO;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>먹을꺼 내놔 홈페이지</title>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"./RESOUCE/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"./RESOUCE/js/bootstrap.min.js\"></script>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./RESOUCE/css/indexjsp.css\"></link>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("\t\t<a class=\"navbar-brand\"  href=\"index.jsp\">Home</a>\n");
      out.write("\t\t<p class=\"navbar-text\" id=\"demo\">현재위치가 비활성화 입니다.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("      \t");

			MemberVO member  = (MemberVO)session.getAttribute("member");
			if(member != null){
				
		
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님 로그인중</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"logout.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span>  로그아웃</a></li>\n");
      out.write("\t\t\t");
 if(member.getDivision().equals("0")){
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"user_modified.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span>  회원정보수정</a></li>\n");
      out.write("\t\t\t");
 } else {
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"seller_modified.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span>  회원정보수정</a></li>\n");
      out.write("\t\t\t");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
}else{ // 세션 로그인 안했을때 안보여줌
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"memberSaleList.do\"><span class=\"glyphicon glyphicon-log-in\"></span> rr</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"user_signup.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> 회원가입</a></li>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("<div class=\"container-fluid text-center\">    \n");
      out.write("  <div class=\"row content bg-1\">\n");
      out.write("      <img src=\"./IMAGE/food.jpg\" class=\"img-circle\" alt=\"Bird\" width=\"200\" height=\"200\">\n");
      out.write("      <h1 class=\"margin\">먹을꺼 내놔</h1>\n");
      out.write("      \n");
      out.write("\t\t<form class=\"navbar-form navbar-center\" role=\"search\">\n");
      out.write("        \t<div class=\"form-group input-group\">\n");
      out.write("          \t\t<input type=\"text\" class=\"form-control\" placeholder=\"음식/지역/식당..\">\n");
      out.write("          \t\t<span class=\"input-group-btn\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\"><span class=\"glyphicon glyphicon-search\"></span></button>\n");
      out.write("          \t\t</span>        \n");
      out.write("        \t</div>\n");
      out.write("      \t</form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"row\">\n");
      out.write("  \t<nav class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("  \t\t<div class=\"navbar-collapse collapse\">\n");
      out.write("    \t\t<ul class=\"nav navbar-nav navbar-center\">\n");
      out.write("        \t\t<li><a href=\"#\">치킨</a></li>\n");
      out.write("        \t\t<li><a href=\"#\">중식</a></li>\n");
      out.write("      \t\t\t<li><a href=\"#\">피자</a></li>\n");
      out.write("      \t\t\t<li><a href=\"#\">족발/보쌈</a></li>\n");
      out.write("      \t\t\t<li><a href=\"#\">야식</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">찜/탕</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">한식/분식</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">돈가스/일식/회</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">도시락/죽/패스트푸드</a></li>\n");
      out.write("    \t\t</ul>\n");
      out.write("  \t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("  </div>\n");
      out.write("  \t\n");
      out.write(" <div class=\"row content bg-2\">\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\t<div class=\"col-sm-4 col-sm-2\">\n");
      out.write("    <div class=\"thumbnail\">\n");
      out.write("      <img src=\"./IMAGE/food.jpg\" alt=\"...\" class=\"img-thumbnail\" width=\"200\" height=\"200\">\n");
      out.write("      <div class=\"caption\">\n");
      out.write("        <h3>음식1</h3>\n");
      out.write("        <p>...</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"col-sm-4 col-sm-2\">\n");
      out.write("    <div class=\"thumbnail\">\n");
      out.write("      <img src=\"./IMAGE/food.jpg\" alt=\"...\" class=\"img-thumbnail\" width=\"200\" height=\"200\">\n");
      out.write("      <div class=\"caption\">\n");
      out.write("        <h3>음식1</h3>\n");
      out.write("        <p>...</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"col-sm-4 col-sm-2\">\n");
      out.write("    <div class=\"thumbnail\">\n");
      out.write("      <img src=\"./IMAGE/food.jpg\" alt=\"...\" class=\"img-thumbnail\" width=\"200\" height=\"200\">\n");
      out.write("      <div class=\"caption\">\n");
      out.write("        <h3>음식1</h3>\n");
      out.write("        <p>...</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"col-sm-4 col-sm-2\">\n");
      out.write("    <div class=\"thumbnail\">\n");
      out.write("      <img src=\"./IMAGE/food.jpg\" alt=\"...\" class=\"img-thumbnail\" width=\"200\" height=\"200\">\n");
      out.write("      <div class=\"caption\">\n");
      out.write("        <h3>음식1</h3>\n");
      out.write("        <p>...</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write(" </div>\n");
      out.write("</div>\n");
      out.write("<footer class=\"container-fluid text-center\">\n");
      out.write("\t<p>야간 5조 : 황일영,김태영 <a href=\"https://www.google.com\">ilyoung6016@gmail.com</a></p>\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
