/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-12-15 04:42:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.vo.MemberVO;

public final class user_005fsignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>가입 페이지</title>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"./RESOUCE/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"./RESOUCE/js/bootstrap.min.js\"></script>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"./RESOUCE/css/indexjsp.css\"></link>\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("\t\t<a class=\"navbar-brand\"  href=\"index.jsp\">Home</a>\n");
      out.write("\t\t<p class=\"navbar-text\">현재위치가 비활성화 입니다.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("      \n");
      out.write("        ");

			MemberVO member  = (MemberVO)session.getAttribute("member");
			if(member != null){
		
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님 로그인중</a></li>\n");
      out.write("\t\t");
}else{ // 세션 로그인 안했을때 안보여줌
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인</a></li> \n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("      \t\n");
      out.write("        <li><a href=\"user_signup.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> 회원가입</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("    <article class=\"container\">\n");
      out.write("        <div class=\"page-header text-center\">\n");
      out.write("          <h1>회원가입</h1>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6 col-md-offset-3\">\n");
      out.write("          <form class=\"form-signin\" method=\"post\" action=\"memberUserInsert.do\" role=\"form\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"Email\">이메일 주소</label>\n");
      out.write("              <input type=\"email\" name=\"mail\" class=\"form-control\" placeholder=\"이메일 주소\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"Password\">비밀번호</label>\n");
      out.write("              <input type=\"password\" name=\"passwd\" class=\"form-control\" placeholder=\"비밀번호\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"Name\">이름</label>\n");
      out.write("              <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"이름\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"Address\">주소</label>\n");
      out.write("              <input type=\"text\" name=\"address\" class=\"form-control\" placeholder=\"주소\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("           <div class=\"form-group\">\n");
      out.write("              <label for=\"Phone\">전화번호</label>\n");
      out.write("              <input type=\"text\" name=\"phone\" class=\"form-control\" placeholder=\"휴대폰입력 ('-'제외)\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("    \t\t\n");
      out.write("    \t\t<div class=\"form-group\">\n");
      out.write("    \t\t<label for=\"Division\">가입자 구분</label>\n");
      out.write("    \t\t\t<div class=\"radio\">\n");
      out.write(" \t\t\t\t\t <label>\n");
      out.write("    \t\t\t\t\t<input type=\"radio\" name=\"division\" value=\"0\" data-toggle=\"collapse\" data-target=\"#collapseExample\" aria-expanded=\"false\" aria-controls=\"collapseExample\" checked>\n");
      out.write("    \t\t\t\t\t\t구매자\n");
      out.write("  \t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"radio\">\n");
      out.write("  \t\t\t\t\t<label>\n");
      out.write("    \t\t\t\t\t\t<input type=\"radio\" name=\"division\" value=\"1\" data-toggle=\"collapse\" data-target=\"#collapseExample\" aria-expanded=\"false\" aria-controls=\"collapseExample\">\n");
      out.write("   \t\t\t\t\t\t \t판매자\n");
      out.write(" \t\t\t\t\t </label>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("    \t\t</div>\n");
      out.write("    \t\t\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"collapseExample\">\n");
      out.write("  \t\t\t\t<div class=\"well-default\">\n");
      out.write("  \t\t\t\t\n");
      out.write("    \t\t\t\t<div class=\"form-group\">\n");
      out.write("              \t\t\t<label for=\"SelName\">식당이름</label>\n");
      out.write("              \t\t\t<input type=\"text\" name=\"sellername\" class=\"form-control\" placeholder=\"식당이름\" >\n");
      out.write("           \t\t\t </div>\n");
      out.write("           \t\t\t \n");
      out.write("           \t\t\t <div class=\"form-group\">\n");
      out.write("              \t\t\t<label for=\"SelAddress\">식당주소</label>\n");
      out.write("              \t\t\t<input type=\"text\" name=\"selleraddress\" class=\"form-control\" placeholder=\"식당주소\" >\n");
      out.write("           \t\t\t </div>\n");
      out.write("           \t\t\t \n");
      out.write("           \t\t\t <div class=\"form-group\">\n");
      out.write("              \t\t\t<label for=\"SelHours\">영업시간</label>\n");
      out.write("              \t\t\t<input type=\"text\" name=\"sellerhours\" class=\"form-control\" placeholder=\"영업시간\" >\n");
      out.write("           \t\t\t </div>\n");
      out.write("           \t\t\t \n");
      out.write("           \t\t\t <div class=\"form-group\">\n");
      out.write("              \t\t\t<label for=\"SelPhone\">식당전화번호</label>\n");
      out.write("              \t\t\t<input type=\"text\" name=\"sellerphone\" class=\"form-control\" placeholder=\"식당전화번호('-'제외)\" >\n");
      out.write("           \t\t\t </div>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("    \t\t\n");
      out.write("            <div class=\"form-group text-center\">\n");
      out.write("              <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">가입</button>\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </article>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
